spring:
  profiles:
    active: dev
  application:
    name: ucenter-micro-service        
        
feign:
  hystrix:
    enabled: true
           
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.djn.cn.op.cloud.ucenter.micro.service.*.entity

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#mapper
#mappers 多个接口时逗号隔开
mapper:
 mappers: com.djn.cn.op.cloud.ucenter.micro.service.base.dao.MyMapper
 mapper: 
   not-empty: true
   identity: MYSQL